version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: [
    "uvicorn", "app.main:app",
    "--host", "0.0.0.0",
    "--port","8000"
    ]
    environment:
      - API_REDIS_HOST=redis
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - /var/lib/docker/volumes/internship-meduzzen_postgres_data/_data

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    env_file:
      - .env

volumes:
  postgres_data:
